// Generated by CoffeeScript 1.6.2
var echo, filled, spawn, split,
  __slice = [].slice;

spawn = require("child_process").spawn;

echo = function(child) {
  child.stderr.pipe(process.stderr);
  return child.stdout.pipe(process.stdout);
};

split = function(string) {
  return string.split(" ");
};

filled = function(string) {
  return string.length > 0;
};

exports["do"] = function() {
  var queue, _;

  _ = arguments[0], queue = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
  return queue.map(split).forEach(function(array, index) {
    console.log('➤➤', queue[index]);
    return echo(spawn(array[0], array.slice(1)));
  });
};
