// Generated by CoffeeScript 1.6.2
var echo, filled, spawn, split;

spawn = require("child_process").spawn;

echo = function(child) {
  child.stderr.pipe(process.stderr);
  return child.stdout.pipe(process.stdout);
};

split = function(string) {
  return string.split(" ");
};

filled = function(string) {
  return string.length > 0;
};

exports.run = function(queue) {
  return queue.map(split).forEach(function(array, index) {
    console.log('➤➤', queue[index]);
    return echo(spawn(array[0], array.slice(1)));
  });
};

exports.read = function(string) {
  var queue;

  queue = string.split('\n').filter(filled);
  return exports.run(queue);
};
